_target_: src.tuners.DPOCausalLMTuner
hparams:
  dpo_beta:
    low: 1e-2
    high: 1.0
    log: False
  lr:
    low: 5e-8
    high: 5e-7
    log: False
  weight_decay:
    low: 1e-2
    high: 1e-1
    log: False
  warmup_ratio:
    low: 1e-2
    high: 1e-1
    log: False
  eta_min_ratio:
    low: 5e-3
    high: 5e-2
    log: False

tracking_direction: ${tracking_direction}
seed: ${seed}
num_trials: ${num_trials}
hparams_save_path: ${hparams_save_path}