_target_: src.architectures.CPTCausalLMArchitecture
model: ${model}
pretrained_model_name: ${pretrained_model_name}
is_sft: ${is_sft}
is_preprocessed: ${is_preprocessed}
custom_data_encoder_path: ${custom_data_encoder_path}
left_padding: ${left_padding}
strategy: ${strategy}
lr: ${lr}
weight_decay: ${weight_decay}
warmup_ratio: ${warmup_ratio}
eta_min_ratio: ${eta_min_ratio}
interval: ${interval}
options: ${options}
target_max_length: ${target_max_length}
target_min_length: ${target_min_length}
per_device_save_path: ${per_device_save_path}
target_column_name: ${target_column_name}
