_target_: src.datasets.dpo_dataset.StructuralDataset
data_path: ${connected_dir}/dpo_data
split: ${split.train}
split_ratio: ${split_ratio}
seed: ${seed}
is_preprocessed: ${is_preprocessed}
instruction_column_name: ${instruction_column_name}
data_column_name: ${data_column_name}
target_a_column_name: ${target_a_column_name}
target_b_column_name: ${target_b_column_name}
preference_column_name: ${preference_column_name}
num_devices: ${devices}
batch_size: ${batch_size}
pretrained_model_name: ${pretrained_model_name}
custom_data_encoder_path: ${custom_data_encoder_path}
left_padding: ${left_padding}
data_max_length: ${data_max_length}
target_max_length: ${target_max_length}
