defaults:
  - hydra: hydra

run_name: soft_voting
work_dir: ${hydra:runtime.cwd}

package_name: upstage-ir
connected_dir: ${oc.env:CONNECTED_DIR}/${package_name}
voted_name: soft_voting

voted_logit: ${connected_dir}/logits/${voted_name}.pickle
voted_prediction: ${connected_dir}/preds/${voted_name}.pickle

votings:
  logit1: 0.5
  logit2: 0.5